### ISSUE TITLE
How to start

### ISSUE THREAD

**Issue by tatjana19** [astrapi69/redundant-file-entries-resolver#2]
Hi there, can you describe how to start the application?

**Comment by astrapi69** [comment]
The main application class for start the application is:
de.alpharogroup.duplicate.files.desktoppane.MainApplication

you can start from eclipse:

![auswahl_002](https://cloud.githubusercontent.com/assets/1822320/20465017/23556e00-af54-11e6-97e5-675720030b8f.png)

**Comment by astrapi69** [comment]
There is even a maven profile for release and there all executable files are created with installer. 
You can run the profile in eclipse:

![auswahl_004](https://cloud.githubusercontent.com/assets/1822320/20465053/ecfbf8c8-af54-11e6-8a06-b8e09486eab9.png)
